import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:tima/app/core/constants/colorConst.dart';
import 'package:tima/app/core/constants/textconst.dart';
import 'package:tima/app/feature/Auth/register/screen/register.dart';
import 'package:tima/app/feature/NavBar/Admin/screen/requestAdmin.dart';
import 'package:tima/app/feature/NavBar/home/homeNavBar.dart';
import 'package:tima/app/feature/drawerPage/inquiry/inquiryDetails/controller/inquiryDetailController.dart';
import 'package:tima/app/feature/visit/visitDetails/visitDetail.dart';
import 'package:tima/app/router/routeParams/inquiryDetailParams.dart';
import 'package:tima/app/router/routeParams/nextVisitParams.dart';
import 'package:tima/app/router/routes/routerConst.dart';

class InquiryDeatil extends StatefulWidget {
  final InquiryDetailParams inquiryDetailParams;
  const InquiryDeatil({super.key, required this.inquiryDetailParams});

  @override
  State<InquiryDeatil> createState() => _InquiryDeatilState();
}

class _InquiryDeatilState extends InquiryDetailController {
  @override
  void initState() {
    getEnqueryDetailsApi();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
            backgroundColor: Colors.white,
            elevation: 0,
            shape: const RoundedRectangleBorder(
              borderRadius: BorderRadius.vertical(
                bottom: Radius.circular(30),
              ),
            ),
            leading: Padding(
              padding: const EdgeInsets.only(left: 15, top: 10, bottom: 3),
              child: Container(
                decoration: const BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.all(
                    Radius.circular(100),
                  ),
                ),
                child: IconButton(
                  icon: const Icon(
                    Icons.arrow_back_outlined,
                    color: Colors.black,
                  ),
                  padding: const EdgeInsets.all(0),
                  onPressed: () {
                    // GoRouter.of(context).goNamed(routerConst.homeNavBar);
                    Navigator.of(context)
                        .push(MaterialPageRoute(builder: (_) => HomeNavBar()));
                  },
                ),
              ),
            ),
            centerTitle: true,
            title: txtHelper().heading1Text('ENQUIERY DETAILS', 23, blueColor)),
        body: Container(
          child: ListView.builder(
              itemCount: getEnqList.length,
              itemBuilder: (context, index) {
                return Container(
                  padding: const EdgeInsets.all(8.0),
                  width: MediaQuery.of(context).size.width,
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Padding(
                        padding: const EdgeInsets.all(5.0),
                        child: Text(
                          "Generated On : ${getEnqList[index].dateTime}",
                          style: const TextStyle(
                              fontSize: 14, fontWeight: FontWeight.bold),
                        ),
                      ),
                      Padding(
                        padding: const EdgeInsets.all(5.0),
                        child: Text(
                          "Generated By : ${getEnqList[index].userName},}",
                          style: const TextStyle(
                              fontSize: 14, fontWeight: FontWeight.bold),
                        ),
                      ),
                      Padding(
                        padding: const EdgeInsets.all(5.0),
                        child: Text(
                          "Contact No. : ${getEnqList[index].userMobile}",
                          style: const TextStyle(
                              fontSize: 15, fontWeight: FontWeight.bold),
                        ),
                      ),
                      Padding(
                        padding: const EdgeInsets.all(5.0),
                        child: Text(
                          "Enquery Type : ${getEnqList[index].enqTypeName}",
                          style: const TextStyle(
                              fontSize: 14, fontWeight: FontWeight.bold),
                        ),
                      ),
                      Padding(
                        padding: const EdgeInsets.all(5.0),
                        child: Text(
                          "Enquiry For : ${getEnqList[index].personName},${getEnqList[index].branchName}",
                          style: const TextStyle(
                              fontSize: 14, fontWeight: FontWeight.bold),
                        ),
                      ),
                      Padding(
                        padding: const EdgeInsets.all(5.0),
                        child: Text(
                          "Contact No. : ${getEnqList[index].personMobile}",
                          style: const TextStyle(
                              fontSize: 15, fontWeight: FontWeight.bold),
                        ),
                      ),
                      Padding(
                        padding: const EdgeInsets.all(5.0),
                        child: Text(
                          "Product/Service : ${getEnqList[index].productServiceType} (${getEnqList[index].productServiceName})",
                          style: const TextStyle(
                              fontSize: 15, fontWeight: FontWeight.bold),
                        ),
                      ),

                      Padding(
                        padding: const EdgeInsets.all(5.0),
                        child: Text(
                          "Client: ${getEnqList[index].client} ",
                          style: const TextStyle(
                              fontSize: 15, fontWeight: FontWeight.bold),
                        ),
                      ),
                      Padding(
                        padding: const EdgeInsets.all(5.0),
                        child: Text(
                          "Contact Person : ${getEnqList[index].contactPerson} ",
                          style: const TextStyle(
                              fontSize: 15, fontWeight: FontWeight.bold),
                        ),
                      ),
                      Padding(
                        padding: const EdgeInsets.all(5.0),
                        child: Text(
                          "Contact No.: ${getEnqList[index].contactNo} ",
                          style: const TextStyle(
                              fontSize: 15, fontWeight: FontWeight.bold),
                        ),
                      ),

                      //========-
                      Padding(
                        padding: const EdgeInsets.all(5.0),
                        child: Text(
                          "Client/Vendor Name : ${getEnqList[index].currentVendor}",
                          style: const TextStyle(
                              fontSize: 15, fontWeight: FontWeight.bold),
                        ),
                      ),
                      Padding(
                        padding: const EdgeInsets.all(5.0),
                        child: Text(
                          "Current price : ${getEnqList[index].currentPrice}",
                          style: const TextStyle(
                              fontSize: 15, fontWeight: FontWeight.bold),
                        ),
                      ),

                      Padding(
                        padding: const EdgeInsets.all(5.0),
                        child: Text(
                          "Target Business : ${getEnqList[index].targetBusiness}",
                          style: const TextStyle(
                              fontSize: 15, fontWeight: FontWeight.bold),
                        ),
                      ),

                      Padding(
                        padding: const EdgeInsets.all(5.0),
                        child: Text(
                          "Remark: ${getEnqList[index].remark} ",
                          style: const TextStyle(
                              fontSize: 15, fontWeight: FontWeight.bold),
                        ),
                      ),
                      Padding(
                        padding: const EdgeInsets.all(5.0),
                        child: Text(
                          "Status: ${getEnqList[index].opStatus} ",
                          style: const TextStyle(
                              fontSize: 15, fontWeight: FontWeight.bold),
                        ),
                      ),
                      const SizedBox(
                        height: 20,
                      ),
                      widget.inquiryDetailParams.type == "generated"
                          ? Flex(
                              direction: Axis.horizontal,
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              children: [
                                  getEnqList[index].opStatus == "closed"
                                      ? GestureDetector(
                                          onTap: () {
                                            Navigator.of(context)
                                                .push(MaterialPageRoute(
                                                    builder: (_) => VisitDeatil(
                                                          visitDetailScreenParams:
                                                              VisitDetailScreenParams(
                                                                  indexlistno:
                                                                      getEnqList[
                                                                              index]
                                                                          .id,
                                                                  name: getEnqList[
                                                                          index]
                                                                      .personName),
                                                        )));
                                            // GoRouter.of(context).goNamed(
                                            //     routerConst.visitDetailScreen,
                                            //     extra: VisitDetailScreenParams(
                                            //         indexlistno:
                                            //             getEnqList[index].id,
                                            //         name: getEnqList[index]
                                            //             .personName));
                                          },
                                          child: Container(
                                            height: 40,
                                            width: MediaQuery.of(context)
                                                    .size
                                                    .width *
                                                0.4,
                                            alignment: Alignment.center,
                                            padding: const EdgeInsets.all(8.0),
                                            color: colorConst.orangeColour,
                                            child: const Text(
                                              "View Detail",
                                              style: TextStyle(
                                                  color: Colors.white,
                                                  fontWeight: FontWeight.bold,
                                                  letterSpacing: 0.8),
                                            ),
                                          ))
                                      : Container()
                                ])
                          : Flex(
                              direction: Axis.horizontal,
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              children: [
                                  getEnqList[index].opStatus == "closed"
                                      ? GestureDetector(
                                          onTap: () {
                                            VisitDeatil(
                                              visitDetailScreenParams:
                                                  VisitDetailScreenParams(
                                                      indexlistno:
                                                          getEnqList[index].id,
                                                      name: getEnqList[index]
                                                          .personName),
                                            );
                                            // GoRouter.of(context).goNamed(
                                            //     routerConst.visitDetailScreen,
                                            //     extra: VisitDetailScreenParams(
                                            //         indexlistno:
                                            //             getEnqList[index].id,
                                            //         name: getEnqList[index]
                                            //             .personName));
                                          },
                                          child: Container(
                                            height: 40,
                                            width: MediaQuery.of(context)
                                                    .size
                                                    .width *
                                                0.4,
                                            alignment: Alignment.center,
                                            padding: const EdgeInsets.all(8.0),
                                            color: colorConst.orangeColour,
                                            child: const Text(
                                              "View Detail",
                                              style: TextStyle(
                                                  color: Colors.white,
                                                  fontWeight: FontWeight.bold,
                                                  letterSpacing: 0.8),
                                            ),
                                          ))
                                      : getEnqList[index].clientId == null &&
                                              getEnqList[index].vendorId == null
                                          ? GestureDetector(
                                              onTap: () {
                                                Navigator.of(context).push(
                                                    MaterialPageRoute(
                                                        builder: (_) =>
                                                            RegisterScreen()));
                                                // GoRouter.of(context).goNamed(
                                                //   routerConst.registerScreen,
                                                //   extra: getEnqList[index].id,
                                                // );
                                              },
                                              child: Container(
                                                height: 40,
                                                width: MediaQuery.of(context)
                                                        .size
                                                        .width *
                                                    0.4,
                                                alignment: Alignment.center,
                                                padding:
                                                    const EdgeInsets.all(8.0),
                                                color: Colors.green,
                                                child: const Text(
                                                  "Map Client",
                                                  style: TextStyle(
                                                      color: Colors.white,
                                                      fontWeight:
                                                          FontWeight.bold,
                                                      letterSpacing: 0.8),
                                                ),
                                              ))
                                          : Container(),
                                  getEnqList[index].opStatus == "closed"
                                      ? Container()
                                      : getEnqList[index].clientId == null &&
                                              getEnqList[index].vendorId == null
                                          ? Container()
                                          : GestureDetector(
                                              onTap: () {
                                                Navigator.of(context)
                                                    .pushReplacement(
                                                        MaterialPageRoute(
                                                            builder: (_) =>
                                                                RequestAdmin()));
                                                // GoRouter.of(context).goNamed(
                                                //     routerConst.requestAdmin,
                                                //     extra:
                                                //         getEnqList[index].id);
                                              },
                                              child: Container(
                                                height: 40,
                                                width: MediaQuery.of(context)
                                                        .size
                                                        .width *
                                                    0.4,
                                                alignment: Alignment.center,
                                                padding:
                                                    const EdgeInsets.all(8.0),
                                                color: colorConst.primarycolor,
                                                child: const Text(
                                                  "Visit",
                                                  style: TextStyle(
                                                      color: Colors.white,
                                                      fontWeight:
                                                          FontWeight.bold,
                                                      letterSpacing: 0.8),
                                                ),
                                              ))
                                ]),
                    ],
                  ),
                );
              }),
        ));
  }
}
