import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:provider/provider.dart';
import 'package:tima_app/core/constants/colorConst.dart';
import 'package:tima_app/feature/drawerPage/inquiry/inquiryDetails/controller/inquiryDetailController.dart';
import 'package:tima_app/providers/inquireyProvider/inquiry_provider.dart';
import 'package:tima_app/router/routeParams/inquiryDetailParams.dart';
import 'package:tima_app/router/routeParams/nextVisitParams.dart';
import 'package:tima_app/router/routes/routerConst.dart';

class InquiryDeatil extends StatefulWidget {
  final InquiryDetailParams inquiryDetailParams;
  InquiryDeatil({super.key, required this.inquiryDetailParams});

  @override
  State<InquiryDeatil> createState() => _InquiryDeatilState();
}

class _InquiryDeatilState extends InquiryDetailController {
  @override
  void initState() {
    getInquiryDataFromApi();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          backgroundColor: Colors.white,
          elevation: 0,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.vertical(
              bottom: Radius.circular(30),
            ),
          ),
          leading: Padding(
            padding: const EdgeInsets.only(left: 15, top: 10, bottom: 3),
            child: Container(
              decoration: BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.all(
                  Radius.circular(100),
                ),
              ),
              child: IconButton(
                icon: Icon(
                  Icons.arrow_back_outlined,
                  color: Colors.black,
                ),
                padding: const EdgeInsets.all(0),
                onPressed: () {
                  GoRouter.of(context).goNamed(routerConst.homeNavBar);
                },
              ),
            ),
          ),
          centerTitle: true,
          title: Text(
            'Enquiry Detail',
            style: TextStyle(
                color: Colors.black,
                fontSize: 25,
                fontFamily: 'Comfortaa',
                fontWeight: FontWeight.bold),
          ),
        ),
        body: Consumer<InquiryProvider>(builder: (_, ref, __) {
          if (ref.getenquirydetailload) {
            return const CircularProgressIndicator();
          } else {
            var enquirydetail = ref.inquirydetail.data;
            return Padding(
              padding: const EdgeInsets.all(10.0),
              child: Card(
                elevation: 5,
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(10.0),
                ),
                child: Container(
                  width: MediaQuery.of(context).size.width,
                  child: Padding(
                    padding: const EdgeInsets.all(8.0),
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Padding(
                          padding: const EdgeInsets.all(5.0),
                          child: Text(
                            "Generated On : ${enquirydetail!.dateTime}",
                            style: TextStyle(
                                fontSize: 14, fontWeight: FontWeight.bold),
                          ),
                        ),
                        Padding(
                          padding: const EdgeInsets.all(5.0),
                          child: Text(
                            "Generated By : ${enquirydetail.userName},${enquirydetail.userBranch}",
                            style: TextStyle(
                                fontSize: 14, fontWeight: FontWeight.bold),
                          ),
                        ),
                        Padding(
                          padding: const EdgeInsets.all(5.0),
                          child: Text(
                            "Contact No. : ${enquirydetail.userMobile}",
                            style: TextStyle(
                                fontSize: 15, fontWeight: FontWeight.bold),
                          ),
                        ),
                        Padding(
                          padding: const EdgeInsets.all(5.0),
                          child: Text(
                            "Enquery Type : ${enquirydetail.enqTypeName}",
                            style: TextStyle(
                                fontSize: 14, fontWeight: FontWeight.bold),
                          ),
                        ),
                        Padding(
                          padding: const EdgeInsets.all(5.0),
                          child: Text(
                            "Enquiry For : ${enquirydetail.personName},${enquirydetail.branchName}",
                            style: TextStyle(
                                fontSize: 14, fontWeight: FontWeight.bold),
                          ),
                        ),
                        Padding(
                          padding: const EdgeInsets.all(5.0),
                          child: Text(
                            "Contact No. : ${enquirydetail.personMobile}",
                            style: TextStyle(
                                fontSize: 15, fontWeight: FontWeight.bold),
                          ),
                        ),
                        Padding(
                          padding: const EdgeInsets.all(5.0),
                          child: Text(
                            "Product/Service : ${enquirydetail.productServiceType} (${enquirydetail.productServiceName})",
                            style: TextStyle(
                                fontSize: 15, fontWeight: FontWeight.bold),
                          ),
                        ),

                        Padding(
                          padding: const EdgeInsets.all(5.0),
                          child: Text(
                            "Client: ${enquirydetail.client} ",
                            style: TextStyle(
                                fontSize: 15, fontWeight: FontWeight.bold),
                          ),
                        ),
                        Padding(
                          padding: const EdgeInsets.all(5.0),
                          child: Text(
                            "Contact Person : ${enquirydetail.contactPerson} ",
                            style: TextStyle(
                                fontSize: 15, fontWeight: FontWeight.bold),
                          ),
                        ),
                        Padding(
                          padding: const EdgeInsets.all(5.0),
                          child: Text(
                            "Contact No.: ${enquirydetail.contactNo} ",
                            style: TextStyle(
                                fontSize: 15, fontWeight: FontWeight.bold),
                          ),
                        ),

                        //========-
                        Padding(
                          padding: const EdgeInsets.all(5.0),
                          child: Text(
                            "Client/Vendor Name : ${enquirydetail.currentVendor}",
                            style: TextStyle(
                                fontSize: 15, fontWeight: FontWeight.bold),
                          ),
                        ),
                        Padding(
                          padding: const EdgeInsets.all(5.0),
                          child: Text(
                            "Current price : ${enquirydetail.currentPrice}",
                            style: TextStyle(
                                fontSize: 15, fontWeight: FontWeight.bold),
                          ),
                        ),

                        Padding(
                          padding: const EdgeInsets.all(5.0),
                          child: Text(
                            "Target Buisness : ${enquirydetail.targetBusiness}",
                            style: TextStyle(
                                fontSize: 15, fontWeight: FontWeight.bold),
                          ),
                        ),

                        Padding(
                          padding: const EdgeInsets.all(5.0),
                          child: Text(
                            "Remark: ${enquirydetail.remark} ",
                            style: TextStyle(
                                fontSize: 15, fontWeight: FontWeight.bold),
                          ),
                        ),
                        Padding(
                          padding: const EdgeInsets.all(5.0),
                          child: Text(
                            "Status: ${enquirydetail.opStatus} ",
                            style: TextStyle(
                                fontSize: 15, fontWeight: FontWeight.bold),
                          ),
                        ),
                        SizedBox(
                          height: 20,
                        ),
                        widget.inquiryDetailParams.type == "generated"
                            ? Flex(
                                direction: Axis.horizontal,
                                mainAxisAlignment:
                                    MainAxisAlignment.spaceBetween,
                                children: [
                                    enquirydetail.opStatus == "closed"
                                        ? GestureDetector(
                                            onTap: () {
                                              GoRouter.of(context).goNamed(
                                                  routerConst.visitDetailScreen,
                                                  extra:
                                                      VisitDetailScreenParams(
                                                          indexlistno:
                                                              enquirydetail.id,
                                                          name: enquirydetail
                                                              .personName));
                                            },
                                            child: Container(
                                              height: 40,
                                              width: MediaQuery.of(context)
                                                      .size
                                                      .width *
                                                  0.4,
                                              alignment: Alignment.center,
                                              padding: EdgeInsets.all(8.0),
                                              color: colorConst.orangeColour,
                                              child: Text(
                                                "View Detail",
                                                style: TextStyle(
                                                    color: Colors.white,
                                                    fontWeight: FontWeight.bold,
                                                    letterSpacing: 0.8),
                                              ),
                                            ))
                                        : Container()
                                  ])
                            : Flex(
                                direction: Axis.horizontal,
                                mainAxisAlignment:
                                    MainAxisAlignment.spaceBetween,
                                children: [
                                    enquirydetail.opStatus == "closed"
                                        ? GestureDetector(
                                            onTap: () {
                                              GoRouter.of(context).goNamed(
                                                  routerConst.visitDetailScreen,
                                                  extra:
                                                      VisitDetailScreenParams(
                                                          indexlistno:
                                                              enquirydetail.id,
                                                          name: enquirydetail
                                                              .personName));
                                            },
                                            child: Container(
                                              height: 40,
                                              width: MediaQuery.of(context)
                                                      .size
                                                      .width *
                                                  0.4,
                                              alignment: Alignment.center,
                                              padding: EdgeInsets.all(8.0),
                                              color: colorConst.orangeColour,
                                              child: Text(
                                                "View Detail",
                                                style: TextStyle(
                                                    color: Colors.white,
                                                    fontWeight: FontWeight.bold,
                                                    letterSpacing: 0.8),
                                              ),
                                            ))
                                        : enquirydetail.clientId == null &&
                                                enquirydetail.vendorId == null
                                            ? GestureDetector(
                                                onTap: () {
                                                  GoRouter.of(context).goNamed(
                                                    routerConst.registerScreen,
                                                    extra: enquirydetail.id,
                                                  );
                                                },
                                                child: Container(
                                                  height: 40,
                                                  width: MediaQuery.of(context)
                                                          .size
                                                          .width *
                                                      0.4,
                                                  alignment: Alignment.center,
                                                  padding: EdgeInsets.all(8.0),
                                                  color: Colors.green,
                                                  child: Text(
                                                    "Map Client",
                                                    style: TextStyle(
                                                        color: Colors.white,
                                                        fontWeight:
                                                            FontWeight.bold,
                                                        letterSpacing: 0.8),
                                                  ),
                                                ))
                                            : Container(),
                                    enquirydetail.opStatus == "closed"
                                        ? Container()
                                        : enquirydetail.clientId == null &&
                                                enquirydetail.vendorId == null
                                            ? Container()
                                            : GestureDetector(
                                                onTap: () {
                                                  GoRouter.of(context).goNamed(
                                                      routerConst.requestAdmin,
                                                      extra: enquirydetail.id);
                                                },
                                                child: Container(
                                                  height: 40,
                                                  width: MediaQuery.of(context)
                                                          .size
                                                          .width *
                                                      0.4,
                                                  alignment: Alignment.center,
                                                  padding: EdgeInsets.all(8.0),
                                                  color:
                                                      colorConst.primarycolor,
                                                  child: Text(
                                                    "Visit",
                                                    style: TextStyle(
                                                        color: Colors.white,
                                                        fontWeight:
                                                            FontWeight.bold,
                                                        letterSpacing: 0.8),
                                                  ),
                                                ))
                                  ]),
                      ],
                    ),
                  ),
                ),
              ),
            );
          }
        }));
  }
}
